name: Fetch & filter

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "45 11 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - name: Get yarn cache path
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ env.cache-name }}-
            ${{ runner.os }}-yarn-
            ${{ runner.os }}-
      - name: Install node_modules
        run: yarn install

      - name: Do the fetch
        run: yarn fetch

      - name: Diff changes
        run: git diff HEAD~ HEAD -- results.json > results-change-diff

      - name: Generate change stats
        run: yarn diff-stat

      - name: Add date to index
        run: yarn add-date

      - name: Augment results for listings page
        run: yarn augment

      - name: Produce listing page
        run: yarn build-listing --public-url https://swj.io/landgrab --out-file $(date +%Y-%m-%d).html

      - name: Add & Commit
        uses: EndBug/add-and-commit@v4.2.0
        with:
          add: "results.json src/site/fetch-index.json dist"
          message: "add latest landgrab"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: sterlingwes/gh-pages-deploy-action@v1.1
        with:
          access-token: ${{ secrets.DEPLOY_TOKEN }}
          source-directory: dist
          build-command: yarn build --public-url https://swj.io/landgrab
